# Generated by Django 4.1 on 2023-03-13 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fat',
            name='status',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
