# Generated by Django 4.1 on 2023-03-13 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_fat_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fat',
            name='status',
            field=models.CharField(default='raw', max_length=15, null=True),
        ),
    ]
